version: "1.1"
name: Status Check
env:
  host: 127.0.0.1
  port: 8000
tests:
  correct-call:
    steps:
      - name: GET request
        http:
          url: http://${{env.host}}:${{env.port}}/greeting/Orell?formal=False
          method: GET
          check:
            status: /^20/
  validation-error:
    steps:
      - name: GET request
        http:
          url: http://${{env.host}}:${{env.port}}/greeting/Orell
          method: GET
          check:
            status: "422"